#!/usr/bin/env python3
"""power_input sheet: EMI filter, fuse, TVS, reverse-battery FET, negative clamp.

Stage order is spec sec.4's:  EMI filter -> fuse -> TVS -> reverse-battery
FET -> buck VIN.

Every value on this sheet comes from a simulation block or a BOM tag, and
each part carries its source in a hidden `Source` field so the value and
the reason for it travel together. The EMI filter's topology and values
are emi_filter.cir's, element for element.

TWO PARTS ARE DELIBERATELY NOT DRAWN, and their gates are left on named
nets with nothing driving them:

  Q1 gate  VBAT_REV_GATE   the ideal-diode controller
  Q2 gate  NCLAMP_GATE     the negative clamp's comparator

Neither part has been chosen, and neither pinout can be drawn without
choosing one. This project's rule is that nothing is guessed into copper,
so ERC will report both as unconnected -- correctly. That is the sheet
reporting an open decision, not an oversight, and the text block on the
page says so to whoever opens it next.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import schlib
from schlib import Sheet, pin_xy, PINS

HW = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HW, "power_input.kicad_sch")

RAIL = 80.0        # the battery rail runs straight across at this y
SHUNT = 100.0      # shunt parts sit here, between rail and ground
GND_Y = 125.0


def series(sh, libid, prefix, x, value, fields):
    """A part in the rail: rotated 90 so its pins land on RAIL."""
    ref = sh.place(libid, prefix, x, RAIL, value, rot=90, fields=fields)
    p = PINS[libid]
    a = pin_xy(*p["1"], x, RAIL, 90)
    b = pin_xy(*p["2"], x, RAIL, 90)
    return ref, min(a[0], b[0]), max(a[0], b[0])


def shunt(sh, libid, prefix, x, value, fields, y=SHUNT, rot=0, to_gnd=True):
    """A part from the rail down to ground."""
    ref = sh.place(libid, prefix, x, y, value, rot=rot, fields=fields)
    p = PINS[libid]
    a = pin_xy(*p["1"], x, y, rot)
    b = pin_xy(*p["2"], x, y, rot)
    top, bot = (a, b) if a[1] < b[1] else (b, a)
    sh.wire(top[0], RAIL, top[0], top[1])
    if to_gnd:
        sh.wire(bot[0], bot[1], bot[0], GND_Y)
        sh.gnd(bot[0], GND_Y)
    return ref, top, bot


def build():
    schlib.verify_pins()
    sh = Sheet("Power input and transient protection",
               comments=[
                   "Generated by hw/gen_sheet_power_input.py -- do not hand-edit until it is retired",
                   "EMI filter values are emi_filter.cir element for element",
                   "TVS and clamp: docs/bom_requirements.md tags TVS, NEG-CLAMP",
                   "Q1 is a P-FET with a passive gate network; Q2's gate is undriven -- see the page",
               ],
               ref_base=schlib.REF_BASE["power_input"])

    # ---- input from the connector sheet ----
    sh.hlabel("VBAT_IN", 30, RAIL, shape="input")
    sh.wire(30, RAIL, 48.19, RAIL)

    # ---- fuse ----
    # 20 A, matching the OEM harness fuse 8F1 the metering unit sits behind.
    _, _, f_r = series(sh, "Device:Fuse", "F", 52, "20A",
                       {"Source": "spec sec.2.2 -- OEM harness fuse 8F1 class",
                       })

    # ---- EMI filter, first stage ----
    _, l1_l, l1_r = series(sh, "Device:L", "L", 80, "22uH",
                           {"Source": "emi_filter.cir L1"})
    sh.wire(f_r, RAIL, l1_l, RAIL)

    shunt(sh, "Device:C", "C", 108, "4.7uF",
          {"Source": "emi_filter.cir C1 -- ESR 5 mOhm, ESL 1.5 nH modelled",
           "ESR": "5 mOhm max"})
    sh.wire(l1_r, RAIL, 108, RAIL)
    sh.junction(108, RAIL)

    # ---- EMI filter, second stage: Lf damped by Rf in parallel ----
    _, lf_l, lf_r = series(sh, "Device:L", "L", 138, "0.5uH",
                           {"Source": "emi_filter.cir Lf"})
    sh.wire(108, RAIL, lf_l, RAIL)
    # Rf sits above the rail, across Lf -- the damping that stops the
    # second stage ringing with C2.
    rf_y = RAIL - 15.24
    sh.place("Device:R", "R", 138, rf_y, "120R",
             rot=90, fields={"Source": "emi_filter.cir Rf -- damps Lf"})
    ra = pin_xy(*PINS["Device:R"]["1"], 138, rf_y, 90)
    rb = pin_xy(*PINS["Device:R"]["2"], 138, rf_y, 90)
    for px in (min(ra[0], rb[0]), max(ra[0], rb[0])):
        sh.wire(px, rf_y, px, RAIL)
        sh.junction(px, RAIL)

    shunt(sh, "Device:C", "C", 170, "100nF",
          {"Source": "emi_filter.cir C2 -- ESR 20 mOhm, ESL 0.5 nH modelled",
           "ESR": "20 mOhm max"})
    sh.wire(lf_r, RAIL, 170, RAIL)
    sh.junction(170, RAIL)

    # ---- damping leg: Cd in series with Rd, both to ground ----
    cd_ref, cd_top, cd_bot = shunt(
        sh, "Device:C", "C", 198, "1uF",
        {"Source": "emi_filter.cir Cd -- damping leg, series with Rd"},
        y=SHUNT - 3.81, to_gnd=False)
    rd_y = SHUNT + 11.43
    sh.place("Device:R", "R", 198, rd_y, "2R2",
             fields={"Source": "emi_filter.cir Rd -- damping leg"})
    rda = pin_xy(*PINS["Device:R"]["1"], 198, rd_y, 0)
    rdb = pin_xy(*PINS["Device:R"]["2"], 198, rd_y, 0)
    rtop, rbot = (rda, rdb) if rda[1] < rdb[1] else (rdb, rda)
    sh.wire(cd_bot[0], cd_bot[1], rtop[0], rtop[1])
    sh.wire(rbot[0], rbot[1], rbot[0], GND_Y)
    sh.gnd(rbot[0], GND_Y)
    sh.wire(170, RAIL, 198, RAIL)
    sh.junction(198, RAIL)

    # ---- TVS ----
    shunt(sh, "Device:D_TVS", "D", 232, "SMCJ43CA",
          {"Source": "bom_requirements TVS; load_dump.cir, transient_clamp.cir",
           "MPN": "SMCJ43CA",
           "Note": "43 V standoff clears the 40 V clamped dump; "
                   "1500 W package clamps pulse 2a at 73.3 V vs the buck's 100 V max",
           "Rotation": "bidirectional -- orientation not significant"},
          rot=90)
    sh.wire(198, RAIL, 232, RAIL)
    sh.junction(232, RAIL)
    # A label attaches only if it sits EXACTLY on the wire. Offsetting it
    # for looks detaches it silently: the net keeps its auto-generated
    # name and the schematic reads as connected while the netlist says
    # otherwise. Every label on this sheet is therefore on a wire point.
    sh.label("VBAT_CLAMPED", 240, RAIL)

    # ---- reverse-battery FET: P-CHANNEL, drain to battery, source to load --
    # CORRECTED 22 Sep 2026. reverse_battery.cir has always modelled this
    # stage as "a P-FET held on by a controller that watches the
    # polarity" -- its own header says so, and its switch model closes on
    # positive input polarity. This sheet drew an N-FET with a controller
    # gate left undriven. Another document and executable file
    # disagreeing, found by trying to choose the controller:
    #
    #   The node this FET sits on swings from +73.3 V (pulse 2a, after the
    #   TVS) to -47.8 V (pulse 1, the bidirectional TVS's negative clamp,
    #   which is bidirectional precisely so a reversed battery does not
    #   forward-bias it). No controller IC checked spans that:
    #     LM74700-Q1  ANODE -65 V to +65 V  -- positive side short by 8.3 V
    #     LM5050-1-Q1 IN -0.3 V to +100 V   -- negative side short by 47.5 V,
    #                 and IN draws 320 uA, so a series resistor to protect
    #                 it would corrupt its 20 mV drain-source sense.
    #
    # A P-FET needs no controller: gate to ground through a resistor, a
    # zener gate-to-source. Vgs = -V(load), so it is on whenever the load
    # side is positive and off when it is pulled to zero -- which IS the
    # block's switch model, with no IC ratings on that 121 V swing to
    # violate. What it gives up is recorded on the page.
    q1y = RAIL + 2.54
    # rot 90 puts DRAIN on the left (battery) and SOURCE on the right
    # (load), gate below. The P-channel body diode runs drain to source,
    # so this is the orientation that conducts forward and blocks a
    # reversed battery.
    sh.place("Device:Q_PMOS_GSD", "Q", 268, q1y, "P-ch, |Vds|>=80V", rot=90,
             fields={
                 "Source": "reverse_battery.cir path B -- modelled as a "
                           "P-FET all along",
                 "Note": "Drain to battery, source to load. |Vds| worst "
                         "case is 47.8 V, blocking pulse 1 with the load "
                         "side clamped near zero; 80 V class anyway, by "
                         "the board's own rail rule.",
                 "Rds_on": "<=40 mOhm at Vgs = -4.5 V: 0.2 V at 5 A "
                           "against reverse_battery.cir's 0.3 V "
                           "requirement, and specified at -4.5 V because "
                           "at a 6 V cranking dip that is all the gate "
                           "gets"})
    qp = PINS["Device:Q_PMOS_GSD"]
    q1s = pin_xy(*qp["2"], 268, q1y, 90)
    q1d = pin_xy(*qp["3"], 268, q1y, 90)
    q1g = pin_xy(*qp["1"], 268, q1y, 90)
    sh.wire(232, RAIL, q1d[0], q1d[1])

    # Gate network. The zener clamps Vgs: without it the gate would sit
    # 73.3 V below the source during pulse 2a.
    gy = q1g[1] + 5.0
    sh.wire(q1g[0], q1g[1], q1g[0], gy)
    sh.label("VBAT_REV_GATE", q1g[0], gy, rot=180)
    sh.place("Device:R", "R", q1g[0], gy + 12.0, "47k",
             fields={"Note": "Gate to ground. Carries (73.3 - 12) / 47k = "
                             "1.3 mA through pulse 2a, 32 uA at 13.5 V. "
                             "With Ciss it also sets the turn-off time "
                             "when the load side is pulled to zero -- "
                             "tens of microseconds, which is why the "
                             "negative clamp is sized for this FET "
                             "staying ON through a whole pulse."})
    ra = pin_xy(*PINS["Device:R"]["1"], q1g[0], gy + 12.0, 0)
    rb = pin_xy(*PINS["Device:R"]["2"], q1g[0], gy + 12.0, 0)
    r_top, r_bot = (ra, rb) if ra[1] < rb[1] else (rb, ra)
    sh.wire(q1g[0], gy, r_top[0], r_top[1])
    sh.wire(r_bot[0], r_bot[1], r_bot[0], GND_Y)
    sh.gnd(r_bot[0], GND_Y)
    sh.junction(q1g[0], gy)

    zx = 286.0
    sh.place("Device:D_Zener", "D", zx, RAIL + 6.0, "12V", rot=270,
             fields={"Note": "Cathode to SOURCE, anode to GATE: clamps Vgs "
                             "at -12 V, inside a P-FET's +/-20 V rating, "
                             "whatever the rail does."})
    zk = pin_xy(*PINS["Device:D_Zener"]["1"], zx, RAIL + 6.0, 270)
    za = pin_xy(*PINS["Device:D_Zener"]["2"], zx, RAIL + 6.0, 270)
    sh.wire(za[0], za[1], za[0], gy)
    sh.wire(za[0], gy, q1g[0], gy)
    # The rail is split at the zener's tap -- a wire landing mid-span on
    # another wire does not connect in KiCad 7.
    sh.wire(q1s[0], q1s[1], zx, RAIL)
    sh.wire(zx, RAIL, zk[0], zk[1])
    sh.junction(zx, RAIL)
    q1d = (zx, RAIL)

    # ---- negative clamp: Schottky backstop in parallel with an active FET --
    sh.wire(q1d[0], q1d[1], 305, RAIL)
    shunt(sh, "Device:D_Schottky", "D", 305, "100V 20A",
          {"Source": "bom_requirements NEG-CLAMP (backstop); "
                     "negative_pulses.cir Dneg1",
           "Note": "Carries 13.58 A peak / 14.5 mJ on ISO 7637-2 pulse 1. "
                   "Instant, passive -- holds the node while the comparator "
                   "decides. Cathode to VIN, anode to ground.",
           "Vr": "100 V class. It was 60 V until 22 Sep 2026: rated for "
                 "the negative pulse it exists to catch, and not for pulse "
                 "2a pushing the SAME node to +73.3 V in reverse.",
           "Ipk": "13.58 A measured"},
          rot=270)
    sh.junction(305, RAIL)

    q2y = SHUNT
    q2 = sh.place("Device:Q_NMOS_GSD", "Q", 340, q2y, "100V 10mOhm N-ch",
                  fields={
                      "Source": "bom_requirements NEG-CLAMP; "
                                "negative_pulses.cir Scl1",
                      "Note": "Active clamp. 15 A through 5 mOhm is 75 mV, "
                              "against a -0.3 V rating no junction device "
                              "can meet (0.367 V junction + 0.180 V bulk).",
                      "Vds": "100 V class. It was 40 V until 22 Sep 2026 -- "
                             "sized for the negative pulses it clamps, with "
                             "its drain on a node pulse 2a drives to "
                             "+73.3 V. 40 V had zero margin on the load "
                             "dump alone.",
                      "Rds_on": "10 mOhm max at Vgs=4.5 V"})
    q2s = pin_xy(*qp["2"], 340, q2y, 0)
    q2d = pin_xy(*qp["3"], 340, q2y, 0)
    q2g = pin_xy(*qp["1"], 340, q2y, 0)
    sh.wire(q2d[0], q2d[1], q2d[0], RAIL)
    sh.junction(q2d[0], RAIL)
    sh.wire(305, RAIL, q2d[0], RAIL)
    sh.wire(q2s[0], q2s[1], q2s[0], GND_Y)
    sh.gnd(q2s[0], GND_Y)
    sh.wire(q2g[0], q2g[1], q2g[0] - 15.24, q2g[1])
    sh.label("NCLAMP_GATE", q2g[0] - 15.24, q2g[1])

    # ---- output to the rails sheet ----
    sh.wire(q2d[0], RAIL, 380, RAIL)
    sh.hlabel("VBAT_PROT", 380, RAIL, shape="output")
    sh.label("VBAT_PROT", 364, RAIL)

    # ---- the note that makes the two open decisions visible ----
    sh.text(
        "OPEN -- two gates on this sheet are intentionally undriven, and ERC "
        "will report them:\\n"
        "  VBAT_REV_GATE   ideal-diode controller for Q1. No part chosen. Its "
        "turn-off time is load-bearing\\n"
        "                  (reverse_battery.cir models it with none) but "
        "nothing sources that number yet.\\n"
        "  NCLAMP_GATE     comparator for Q2, sensing VIN against -0.1 V. No "
        "part chosen. Its propagation\\n"
        "                  delay is the last unmodelled term in "
        "negative_pulses.cir -- VIN sits at the\\n"
        "                  Schottky's -0.53 V for exactly that long before "
        "the clamp engages.\\n"
        "Neither pinout can be drawn without choosing a part, and this "
        "project does not guess parts into copper.",
        30, 150, size=1.6)
    sh.text(
        "Stage order is spec sec.4: EMI filter -> fuse -> TVS -> "
        "reverse-battery FET -> buck VIN.\\n"
        "EMI filter values are emi_filter.cir element for element. Every "
        "part carries its source in a hidden Source field.",
        30, 175, size=1.6)
    return sh


if __name__ == "__main__":
    sh = build()
    force = "--force" in sys.argv
    print(sh.write(OUT, force=force))
