#!/usr/bin/env python3
"""power_input sheet: EMI filter, fuse, TVS, reverse-battery FET, negative clamp.

Stage order is spec sec.4's:  EMI filter -> fuse -> TVS -> reverse-battery
FET -> buck VIN.

Every value on this sheet comes from a simulation block or a BOM tag, and
each part carries its source in a hidden `Source` field so the value and
the reason for it travel together. The EMI filter's topology and values
are emi_filter.cir's, element for element.

TWO PARTS ARE DELIBERATELY NOT DRAWN, and their gates are left on named
nets with nothing driving them:

  Q1 gate  VBAT_REV_GATE   the ideal-diode controller
  Q2 gate  NCLAMP_GATE     the negative clamp's comparator

Neither part has been chosen, and neither pinout can be drawn without
choosing one. This project's rule is that nothing is guessed into copper,
so ERC will report both as unconnected -- correctly. That is the sheet
reporting an open decision, not an oversight, and the text block on the
page says so to whoever opens it next.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import schlib
from schlib import Sheet, pin_xy, PINS

HW = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HW, "power_input.kicad_sch")

RAIL = 80.0        # the battery rail runs straight across at this y
SHUNT = 100.0      # shunt parts sit here, between rail and ground
GND_Y = 125.0


def series(sh, libid, prefix, x, value, fields):
    """A part in the rail: rotated 90 so its pins land on RAIL."""
    ref = sh.place(libid, prefix, x, RAIL, value, rot=90, fields=fields)
    p = PINS[libid]
    a = pin_xy(*p["1"], x, RAIL, 90)
    b = pin_xy(*p["2"], x, RAIL, 90)
    return ref, min(a[0], b[0]), max(a[0], b[0])


def shunt(sh, libid, prefix, x, value, fields, y=SHUNT, rot=0, to_gnd=True):
    """A part from the rail down to ground."""
    ref = sh.place(libid, prefix, x, y, value, rot=rot, fields=fields)
    p = PINS[libid]
    a = pin_xy(*p["1"], x, y, rot)
    b = pin_xy(*p["2"], x, y, rot)
    top, bot = (a, b) if a[1] < b[1] else (b, a)
    sh.wire(top[0], RAIL, top[0], top[1])
    if to_gnd:
        sh.wire(bot[0], bot[1], bot[0], GND_Y)
        sh.gnd(bot[0], GND_Y)
    return ref, top, bot


def build():
    schlib.verify_pins()
    sh = Sheet("Power input and transient protection",
               comments=[
                   "Generated by hw/gen_sheet_power_input.py -- do not hand-edit until it is retired",
                   "EMI filter values are emi_filter.cir element for element",
                   "TVS and clamp: docs/bom_requirements.md tags TVS, NEG-CLAMP",
                   "Q1/Q2 gates are intentionally undriven -- see the note on the page",
               ],
               ref_base=schlib.REF_BASE["power_input"])

    # ---- input from the connector sheet ----
    sh.hlabel("VBAT_IN", 30, RAIL, shape="input")
    sh.wire(30, RAIL, 48.19, RAIL)

    # ---- fuse ----
    # 20 A, matching the OEM harness fuse 8F1 the metering unit sits behind.
    _, _, f_r = series(sh, "Device:Fuse", "F", 52, "20A",
                       {"Source": "spec sec.2.2 -- OEM harness fuse 8F1 class",
                       })

    # ---- EMI filter, first stage ----
    _, l1_l, l1_r = series(sh, "Device:L", "L", 80, "22uH",
                           {"Source": "emi_filter.cir L1"})
    sh.wire(f_r, RAIL, l1_l, RAIL)

    shunt(sh, "Device:C", "C", 108, "4.7uF",
          {"Source": "emi_filter.cir C1 -- ESR 5 mOhm, ESL 1.5 nH modelled",
           "ESR": "5 mOhm max"})
    sh.wire(l1_r, RAIL, 108, RAIL)
    sh.junction(108, RAIL)

    # ---- EMI filter, second stage: Lf damped by Rf in parallel ----
    _, lf_l, lf_r = series(sh, "Device:L", "L", 138, "0.5uH",
                           {"Source": "emi_filter.cir Lf"})
    sh.wire(108, RAIL, lf_l, RAIL)
    # Rf sits above the rail, across Lf -- the damping that stops the
    # second stage ringing with C2.
    rf_y = RAIL - 15.24
    sh.place("Device:R", "R", 138, rf_y, "120R",
             rot=90, fields={"Source": "emi_filter.cir Rf -- damps Lf"})
    ra = pin_xy(*PINS["Device:R"]["1"], 138, rf_y, 90)
    rb = pin_xy(*PINS["Device:R"]["2"], 138, rf_y, 90)
    for px in (min(ra[0], rb[0]), max(ra[0], rb[0])):
        sh.wire(px, rf_y, px, RAIL)
        sh.junction(px, RAIL)

    shunt(sh, "Device:C", "C", 170, "100nF",
          {"Source": "emi_filter.cir C2 -- ESR 20 mOhm, ESL 0.5 nH modelled",
           "ESR": "20 mOhm max"})
    sh.wire(lf_r, RAIL, 170, RAIL)
    sh.junction(170, RAIL)

    # ---- damping leg: Cd in series with Rd, both to ground ----
    cd_ref, cd_top, cd_bot = shunt(
        sh, "Device:C", "C", 198, "1uF",
        {"Source": "emi_filter.cir Cd -- damping leg, series with Rd"},
        y=SHUNT - 3.81, to_gnd=False)
    rd_y = SHUNT + 11.43
    sh.place("Device:R", "R", 198, rd_y, "2R2",
             fields={"Source": "emi_filter.cir Rd -- damping leg"})
    rda = pin_xy(*PINS["Device:R"]["1"], 198, rd_y, 0)
    rdb = pin_xy(*PINS["Device:R"]["2"], 198, rd_y, 0)
    rtop, rbot = (rda, rdb) if rda[1] < rdb[1] else (rdb, rda)
    sh.wire(cd_bot[0], cd_bot[1], rtop[0], rtop[1])
    sh.wire(rbot[0], rbot[1], rbot[0], GND_Y)
    sh.gnd(rbot[0], GND_Y)
    sh.wire(170, RAIL, 198, RAIL)
    sh.junction(198, RAIL)

    # ---- TVS ----
    shunt(sh, "Device:D_TVS", "D", 232, "SMCJ43CA",
          {"Source": "bom_requirements TVS; load_dump.cir, transient_clamp.cir",
           "MPN": "SMCJ43CA",
           "Note": "43 V standoff clears the 40 V clamped dump; "
                   "1500 W package clamps pulse 2a at 73.3 V vs the buck's 100 V max",
           "Rotation": "bidirectional -- orientation not significant"},
          rot=90)
    sh.wire(198, RAIL, 232, RAIL)
    sh.junction(232, RAIL)
    # A label attaches only if it sits EXACTLY on the wire. Offsetting it
    # for looks detaches it silently: the net keeps its auto-generated
    # name and the schematic reads as connected while the netlist says
    # otherwise. Every label on this sheet is therefore on a wire point.
    sh.label("VBAT_CLAMPED", 240, RAIL)

    # ---- reverse-battery FET: source to battery, drain to load ----
    q1y = RAIL - 2.54
    # rot 270 puts SOURCE on the left (battery) and DRAIN on the right
    # (load), which is the orientation whose body diode blocks reverse
    # current. rot 90 gives the mirror image and a part that conducts
    # exactly when it should not.
    q1 = sh.place("Device:Q_NMOS_GSD", "Q", 268, q1y, "100V N-ch", rot=270,
                  fields={
                      "Source": "reverse_battery.cir; bom_requirements "
                                "(reverse-battery FET)",
                      "Note": "100 V class -- third revision, raised each "
                              "time the clamp moved. Source to battery so "
                              "the body diode blocks reverse current.",
                      "Rds_on": "8 mOhm modelled"})
    qp = PINS["Device:Q_NMOS_GSD"]
    q1s = pin_xy(*qp["2"], 268, q1y, 270)
    q1d = pin_xy(*qp["3"], 268, q1y, 270)
    q1g = pin_xy(*qp["1"], 268, q1y, 270)
    sh.wire(232, RAIL, q1s[0], q1s[1])
    sh.wire(q1g[0], q1g[1], q1g[0], q1g[1] - 7.62)
    sh.label("VBAT_REV_GATE", q1g[0], q1g[1] - 7.62)

    # ---- negative clamp: Schottky backstop in parallel with an active FET --
    sh.wire(q1d[0], q1d[1], 305, RAIL)
    shunt(sh, "Device:D_Schottky", "D", 305, "60V 20A",
          {"Source": "bom_requirements NEG-CLAMP (backstop); "
                     "negative_pulses.cir Dneg1",
           "Note": "Carries 13.58 A peak / 14.5 mJ on ISO 7637-2 pulse 1. "
                   "Instant, passive -- holds the node while the comparator "
                   "decides. Cathode to VIN, anode to ground.",
           "Ipk": "13.58 A measured"},
          rot=270)
    sh.junction(305, RAIL)

    q2y = SHUNT
    q2 = sh.place("Device:Q_NMOS_GSD", "Q", 340, q2y, "40V 5mOhm N-ch",
                  fields={
                      "Source": "bom_requirements NEG-CLAMP; "
                                "negative_pulses.cir Scl1",
                      "Note": "Active clamp. 15 A through 5 mOhm is 75 mV, "
                              "against a -0.3 V rating no junction device "
                              "can meet (0.367 V junction + 0.180 V bulk).",
                      "Rds_on": "10 mOhm max at Vgs=4.5 V"})
    q2s = pin_xy(*qp["2"], 340, q2y, 0)
    q2d = pin_xy(*qp["3"], 340, q2y, 0)
    q2g = pin_xy(*qp["1"], 340, q2y, 0)
    sh.wire(q2d[0], q2d[1], q2d[0], RAIL)
    sh.junction(q2d[0], RAIL)
    sh.wire(305, RAIL, q2d[0], RAIL)
    sh.wire(q2s[0], q2s[1], q2s[0], GND_Y)
    sh.gnd(q2s[0], GND_Y)
    sh.wire(q2g[0], q2g[1], q2g[0] - 15.24, q2g[1])
    sh.label("NCLAMP_GATE", q2g[0] - 15.24, q2g[1])

    # ---- output to the rails sheet ----
    sh.wire(q2d[0], RAIL, 380, RAIL)
    sh.hlabel("VBAT_PROT", 380, RAIL, shape="output")
    sh.label("VBAT_PROT", 364, RAIL)

    # ---- the note that makes the two open decisions visible ----
    sh.text(
        "OPEN -- two gates on this sheet are intentionally undriven, and ERC "
        "will report them:\\n"
        "  VBAT_REV_GATE   ideal-diode controller for Q1. No part chosen. Its "
        "turn-off time is load-bearing\\n"
        "                  (reverse_battery.cir models it with none) but "
        "nothing sources that number yet.\\n"
        "  NCLAMP_GATE     comparator for Q2, sensing VIN against -0.1 V. No "
        "part chosen. Its propagation\\n"
        "                  delay is the last unmodelled term in "
        "negative_pulses.cir -- VIN sits at the\\n"
        "                  Schottky's -0.53 V for exactly that long before "
        "the clamp engages.\\n"
        "Neither pinout can be drawn without choosing a part, and this "
        "project does not guess parts into copper.",
        30, 150, size=1.6)
    sh.text(
        "Stage order is spec sec.4: EMI filter -> fuse -> TVS -> "
        "reverse-battery FET -> buck VIN.\\n"
        "EMI filter values are emi_filter.cir element for element. Every "
        "part carries its source in a hidden Source field.",
        30, 175, size=1.6)
    return sh


if __name__ == "__main__":
    sh = build()
    force = "--force" in sys.argv
    print(sh.write(OUT, force=force))
