#!/usr/bin/env python3
"""Generate the KiCad project skeleton for the genset ECU.

Why a generator and not a hand-drawn root sheet: the sheet list, the
sheet-to-simulation-block mapping and the BOM requirement tags all have to
stay in step with sim/blocks/ and docs/bom_requirements.md, and a root
sheet edited by hand drifts from them silently. This script is the single
place that list lives. Re-running it rewrites ONLY the root sheet and any
child sheet that does not exist yet -- a child sheet with content in it is
never touched, so schematic work done in Eeschema is safe.

KiCad 7 (.kicad_sch, version 20230121). Checked against the installed
kicad-cli 7.0.11.
"""
import json
import os
import sys
import uuid

HW = os.path.dirname(os.path.abspath(__file__))
PROJECT = "ecu25kva"

# Sheet order is signal order: power in, rails, brain, then outputs,
# inputs, comms, and finally the connector everything lands on.
SHEETS = [
    ("power_input", "Power input and transient protection",
     "emi_filter, transient_clamp, load_dump, negative_pulses, reverse_battery",
     "TVS, NEG-CLAMP"),
    ("rails", "Buck pre-regulator, 3V3 and 5V_SENSOR rails",
     "buck_preregulator, mcu_pdn, sensor_rail",
     "PDN-BULK, SENSOR-PTC"),
    ("mcu", "S32K148, supervisor and fail-safe gating",
     "supervisor, mcu_pdn",
     "GATE-PULLDOWN"),
    ("injector", "Injector drive: boost rail, high sides, low sides",
     "boost_converter, injector_boost, injector_turnoff",
     ""),
    ("metering_egr", "Fuel metering unit and EGR actuator",
     "metering_unit_pwm, egr_hbridge",
     "MU-ISENSE, EGR-DRIVER"),
    ("sensors_analog", "Analog sensor front-ends",
     "sensor_ratiometric, sensor_differential, ntc_frontend, battery_sense",
     ""),
    ("speed_inputs", "Crank VR conditioner and cam front-end",
     "vr_conditioner, cam_frontend",
     ""),
    ("discrete_io", "Switch inputs, trip-module sense, relay drivers",
     "discrete_input, trip_module_sense, relay_driver",
     ""),
    ("can", "Dual CAN, J1939 250 kbit/s",
     "can_termination",
     "CAN-TERM"),
    ("connector", "94-way Bosch connector and harness mapping",
     "",
     ""),
]

# A3 in mm. Sheet symbols are laid out two columns down the page.
PAPER = "A3"
COL_X = (25.4, 165.1)
ROW_Y0, ROW_DY = 30.48, 38.1
SHEET_W, SHEET_H = 101.6, 25.4


def u():
    return str(uuid.uuid4())


def sheet_symbol(name, fname, desc, blocks, tags, x, y):
    """One hierarchical sheet symbol on the root page."""
    def prop(key, val, idx, dy, justify, hide=False):
        h = " hide" if hide else ""
        return (f'    (property "{key}" "{val}" (id {idx}) (at {x} {y + dy:.2f} 0)\n'
                f'      (effects (font (size 1.27 1.27)) (justify {justify})'
                f'{h})\n    )')
    parts = [
        f'  (sheet (at {x} {y}) (size {SHEET_W} {SHEET_H}) (fields_autoplaced)',
        '    (stroke (width 0.1524) (type solid))',
        '    (fill (color 0 0 0 0.0000))',
        f'    (uuid {u()})',
        prop("Sheetname", name, 0, -0.7112, "left bottom"),
        prop("Sheetfile", fname, 1, SHEET_H + 0.5588, "left top"),
        prop("Description", desc, 2, 0, "left", hide=True),
        prop("SimBlocks", blocks, 3, 0, "left", hide=True),
        prop("BomTags", tags, 4, 0, "left", hide=True),
        '  )',
    ]
    return "\n".join(parts)


def write_root():
    body = [f'(kicad_sch (version 20230121) (generator ecu25kva_gen)',
            f'  (uuid {u()})',
            f'  (paper "{PAPER}")',
            '  (title_block',
            '    (title "Genset ECU -- 25 kVA Kirloskar 3GK550ETA 4SR1")',
            '    (company "ecu25kva")',
            '    (comment 1 "Root sheet -- generated by hw/gen_project.py")',
            '    (comment 2 "Every sheet maps to blocks in sim/blocks/ and tags in docs/bom_requirements.md")',
            '  )',
            '  (lib_symbols)']
    instances = []
    for i, (name, desc, blocks, tags) in enumerate(SHEETS):
        x = COL_X[i // 5]
        y = ROW_Y0 + (i % 5) * ROW_DY
        body.append(sheet_symbol(name, f"{name}.kicad_sch", desc, blocks,
                                 tags, x, y))
        instances.append(f'    (path "/{u()}" (page "{i + 2}"))')
    body.append('  (sheet_instances')
    body.append('    (path "/" (page "1"))')
    body.append('  )')
    body.append(')')
    path = os.path.join(HW, f"{PROJECT}.kicad_sch")
    with open(path, "w") as f:
        f.write("\n".join(body) + "\n")
    return path


def write_child(name, desc):
    """Create an empty child sheet, but NEVER overwrite one with content."""
    path = os.path.join(HW, f"{name}.kicad_sch")
    if os.path.exists(path):
        if os.path.getsize(path) > 400:
            return path, "kept (has content)"
        return path, "kept"
    with open(path, "w") as f:
        f.write(f'''(kicad_sch (version 20230121) (generator ecu25kva_gen)
  (uuid {u()})
  (paper "{PAPER}")
  (title_block
    (title "{desc}")
    (company "ecu25kva")
    (comment 1 "Sheet: {name}")
  )
  (lib_symbols)
  (sheet_instances
    (path "/" (page "1"))
  )
)
''')
    return path, "created"


def write_project():
    path = os.path.join(HW, f"{PROJECT}.kicad_pro")
    if os.path.exists(path):
        return path, "kept"
    pro = {
        "board": {"design_settings": {}},
        "libraries": {"pinned_footprint_libs": [], "pinned_symbol_libs": []},
        "meta": {"filename": f"{PROJECT}.kicad_pro", "version": 1},
        "net_settings": {"classes": [{"name": "Default", "clearance": 0.2,
                                      "track_width": 0.25}]},
        "schematic": {"legacy_lib_dir": "", "legacy_lib_list": []},
        "sheets": [],
        "text_variables": {},
    }
    with open(path, "w") as f:
        json.dump(pro, f, indent=2)
    return path, "created"


def write_sym_lib_table():
    """Point the project at its own symbol library.

    The S32K148 has no symbol in KiCad 7's stock libraries (checked: no
    S32K anywhere under /usr/share/kicad/symbols). Several other parts
    here are specified by property rather than by part number, so they
    need project-local symbols too.
    """
    path = os.path.join(HW, "sym-lib-table")
    if os.path.exists(path):
        return path, "kept"
    with open(path, "w") as f:
        f.write('(sym_lib_table\n'
                '  (lib (name "ecu25kva")(type "KiCad")'
                '(uri "${KIPRJMOD}/lib/ecu25kva.kicad_sym")'
                '(options "")(descr "Project symbols -- parts with no stock '
                'KiCad symbol, S32K148 included"))\n)\n')
    return path, "created"


if __name__ == "__main__":
    print(f"root      {write_root()}")
    for p, s in (write_project(), write_sym_lib_table()):
        print(f"{s:9} {p}")
    for name, desc, _, _ in SHEETS:
        p, s = write_child(name, desc)
        print(f"{s:9} {os.path.basename(p)}")
